"""refactor_micro_service_tables

Revision ID: 059b02b3009b
Revises: b74b4b204dfe
Create Date: 2026-01-16 18:08:06.642062

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '059b02b3009b'
down_revision: Union[str, None] = 'b74b4b204dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('micro_contest_language', sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('micro_contest_language', sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('micro_contest_language', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('micro_contest_language_contest_id_fkey'), 'micro_contest_language', type_='foreignkey')
    op.create_foreign_key(None, 'micro_contest_language', 'contest', ['contest_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('micro_contest_user', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('micro_contest_user', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_organization', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('micro_organization', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_organization', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # Fix micro_organization_member: drop old PK, add id, add new PK, add new columns
    op.execute("ALTER TABLE public.micro_organization_member DROP CONSTRAINT IF EXISTS micro_organization_member_pkey")
    op.add_column('micro_organization_member', sa.Column('id', sa.BigInteger(), sa.Identity(), autoincrement=True, nullable=False))
    op.create_primary_key('micro_organization_member_pkey', 'micro_organization_member', ['id'])
    
    # Add other missing columns
    organization_role_enum = sa.Enum('MEMBER', 'ORG_ADMIN', 'ORG_SUPER_ADMIN', name='organization_role')
    organization_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('micro_organization_member', sa.Column('role', organization_role_enum, server_default='MEMBER', nullable=False))
    op.add_column('micro_organization_member', sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('micro_organization_member', sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('micro_organization_member', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', type_='foreignkey')
    op.drop_constraint(op.f('micro_organization_member_member_id_fkey'), 'micro_organization_member', type_='foreignkey')
    op.create_foreign_key(None, 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_organization_member', 'user', ['member_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('micro_problem_code', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('micro_problem_code', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_problem_code', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.drop_constraint(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.create_foreign_key(None, 'micro_problem_code', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_problem_code', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('micro_userdata', sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('micro_userdata', sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('micro_userdata', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_public_micro_userdata_id'), 'micro_userdata', ['id'], unique=False, schema='public')
    op.drop_constraint(op.f('micro_userdata_user_id_fkey'), 'micro_userdata', type_='foreignkey')
    op.create_foreign_key(None, 'micro_userdata', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('micro_workbook', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('micro_workbook', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('micro_workbook', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_workbook', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.drop_constraint(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.create_foreign_key(None, 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE public.micro_workbook_problem DROP CONSTRAINT IF EXISTS micro_workbook_problem_problem_id_fkey")
    op.execute("ALTER TABLE public.micro_workbook_problem DROP CONSTRAINT IF EXISTS micro_workbook_problem_workbook_id_fkey")
    op.create_foreign_key(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', 'problem', ['problem_id'], ['id'])
    op.create_foreign_key(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    op.alter_column('micro_workbook', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_workbook', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_workbook', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('micro_workbook', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.execute("ALTER TABLE public.micro_userdata DROP CONSTRAINT IF EXISTS micro_userdata_user_id_fkey")
    op.create_foreign_key(op.f('micro_userdata_user_id_fkey'), 'micro_userdata', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_public_micro_userdata_id'), table_name='micro_userdata', schema='public')
    op.alter_column('micro_userdata', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('micro_userdata', 'updated_time')
    op.drop_column('micro_userdata', 'created_time')
    op.execute("ALTER TABLE public.micro_problem_code DROP CONSTRAINT IF EXISTS micro_problem_code_problem_id_fkey")
    op.execute("ALTER TABLE public.micro_problem_code DROP CONSTRAINT IF EXISTS micro_problem_code_user_id_fkey")
    op.create_foreign_key(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('micro_problem_code', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_problem_code', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_problem_code', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.execute("ALTER TABLE public.micro_organization_member DROP CONSTRAINT IF EXISTS micro_organization_member_organization_id_fkey")
    op.execute("ALTER TABLE public.micro_organization_member DROP CONSTRAINT IF EXISTS micro_organization_member_user_id_fkey")
    op.create_foreign_key(op.f('micro_organization_member_member_id_fkey'), 'micro_organization_member', 'user', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('micro_organization_member', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # Revert micro_organization_member changes
    op.drop_column('micro_organization_member', 'updated_time')
    op.drop_column('micro_organization_member', 'created_time')
    op.drop_column('micro_organization_member', 'role')
    op.execute("DROP TYPE IF EXISTS organization_role")

    op.drop_constraint('micro_organization_member_pkey', 'micro_organization_member', type_='primary')
    op.drop_column('micro_organization_member', 'id')
    op.create_primary_key('micro_organization_member_pkey', 'micro_organization_member', ['organization_id', 'member_id'])
    op.alter_column('micro_organization', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_organization', 'created_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_organization', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('micro_contest_user', 'updated_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('micro_contest_user', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.execute("ALTER TABLE public.micro_contest_language DROP CONSTRAINT IF EXISTS micro_contest_language_contest_id_fkey")
    op.create_foreign_key(op.f('micro_contest_language_contest_id_fkey'), 'micro_contest_language', 'contest', ['contest_id'], ['id'])
    op.alter_column('micro_contest_language', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('micro_contest_language', 'updated_time')
    op.drop_column('micro_contest_language', 'created_time')
    # ### end Alembic commands ###
