"""empty message

Revision ID: 1f51d726e37a
Revises: 27f0ac696fec
Create Date: 2025-10-30 10:06:31.363741

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f51d726e37a'
down_revision: Union[str, None] = '27f0ac696fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.drop_constraint(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.create_foreign_key(None, 'micro_problem_code', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_problem_code', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.drop_constraint(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.create_foreign_key(None, 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', 'problem', ['problem_id'], ['id'])
    op.create_foreign_key(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
