"""empty message

Revision ID: 2299ad77eaaa
Revises: 059b02b3009b
Create Date: 2026-01-21 12:32:10.098790

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2299ad77eaaa'
down_revision: Union[str, None] = '059b02b3009b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    # op.execute("CREATE TYPE organization_role AS ENUM ('MEMBER', 'ORG_ADMIN', 'ORG_SUPER_ADMIN')") # Already created in previous migration

    op.drop_constraint('micro_contest_language_contest_id_fkey', 'micro_contest_language', type_='foreignkey')
    op.create_foreign_key(None, 'micro_contest_language', 'contest', ['contest_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index('ix_public_micro_organization_description', table_name='micro_organization')
    op.add_column('micro_organization_member', sa.Column('user_id', sa.Integer(), nullable=False))
    
    # Use existing enum type
    # op.add_column('micro_organization_member', sa.Column('role', sa.Enum('MEMBER', 'ORG_ADMIN', 'ORG_SUPER_ADMIN', name='organization_role'), nullable=False))
    
    # op.add_column('micro_organization_member', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    # op.add_column('micro_organization_member', sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # op.add_column('micro_organization_member', sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_org_member_org_id', 'micro_organization_member', ['organization_id'], unique=False, schema='public')
    op.create_index('ix_org_member_user_id', 'micro_organization_member', ['user_id'], unique=False, schema='public')
    # op.create_index(op.f('ix_public_micro_organization_member_id'), 'micro_organization_member', ['id'], unique=False, schema='public')
    op.create_unique_constraint('uq_org_user', 'micro_organization_member', ['organization_id', 'user_id'], schema='public')
    op.drop_constraint('micro_organization_member_member_id_fkey', 'micro_organization_member', type_='foreignkey')
    op.drop_constraint('micro_organization_member_organization_id_fkey', 'micro_organization_member', type_='foreignkey')
    op.create_foreign_key(None, 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_organization_member', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('micro_organization_member', 'member_id')
    op.drop_constraint('micro_problem_code_problem_id_fkey', 'micro_problem_code', type_='foreignkey')
    op.drop_constraint('micro_problem_code_user_id_fkey', 'micro_problem_code', type_='foreignkey')
    op.create_foreign_key(None, 'micro_problem_code', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_problem_code', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('micro_userdata_user_id_fkey', 'micro_userdata', type_='foreignkey')
    op.create_foreign_key(None, 'micro_userdata', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('micro_workbook_problem_problem_id_fkey', 'micro_workbook_problem', type_='foreignkey')
    op.drop_constraint('micro_workbook_problem_workbook_id_fkey', 'micro_workbook_problem', type_='foreignkey')
    op.create_foreign_key(None, 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    # op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    # op.create_foreign_key('micro_workbook_problem_workbook_id_fkey', 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key('micro_workbook_problem_problem_id_fkey', 'micro_workbook_problem', 'problem', ['problem_id'], ['id'])
    # op.drop_constraint(None, 'micro_userdata', schema='public', type_='foreignkey')
    # op.create_foreign_key('micro_userdata_user_id_fkey', 'micro_userdata', 'user', ['user_id'], ['id'])
    # op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    # op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    # op.create_foreign_key('micro_problem_code_user_id_fkey', 'micro_problem_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key('micro_problem_code_problem_id_fkey', 'micro_problem_code', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.add_column('micro_organization_member', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    # op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    # op.create_foreign_key('micro_organization_member_organization_id_fkey', 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key('micro_organization_member_member_id_fkey', 'micro_organization_member', 'user', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_org_user', 'micro_organization_member', schema='public', type_='unique')
    # op.drop_index(op.f('ix_public_micro_organization_member_id'), table_name='micro_organization_member', schema='public')
    op.drop_index('ix_org_member_user_id', table_name='micro_organization_member', schema='public')
    op.drop_index('ix_org_member_org_id', table_name='micro_organization_member', schema='public')
    # op.drop_column('micro_organization_member', 'updated_time')
    # op.drop_column('micro_organization_member', 'created_time')
    # op.drop_column('micro_organization_member', 'id')
    # op.drop_column('micro_organization_member', 'role')
    op.drop_column('micro_organization_member', 'user_id')
    
    # Drop enum type
    # op.execute("DROP TYPE organization_role")
    
    op.create_index(op.f('ix_public_micro_organization_description'), 'micro_organization', ['description'], unique=False)
    # op.drop_constraint(None, 'micro_contest_language', schema='public', type_='foreignkey')
    # op.create_foreign_key('micro_contest_language_contest_id_fkey', 'micro_contest_language', 'contest', ['contest_id'], ['id'])
    # ### end Alembic commands ###

