"""initial_reset

Revision ID: 348f9671d2e8
Revises: 
Create Date: 2026-02-04 02:30:57.047532

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348f9671d2e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('micro_contest_language_contest_id_fkey'), 'micro_contest_language', type_='foreignkey')
    op.create_foreign_key(None, 'micro_contest_language', 'contest', ['contest_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', type_='foreignkey')
    op.drop_constraint(op.f('micro_organization_member_user_id_fkey'), 'micro_organization_member', type_='foreignkey')
    op.create_foreign_key(None, 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_organization_member', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.drop_constraint(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.create_foreign_key(None, 'micro_problem_code', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_problem_code', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('micro_todo_user_id_fkey'), 'micro_todo', type_='foreignkey')
    op.create_foreign_key(None, 'micro_todo', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('micro_userdata_user_id_fkey'), 'micro_userdata', type_='foreignkey')
    op.create_foreign_key(None, 'micro_userdata', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.drop_constraint(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.create_foreign_key(None, 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', 'problem', ['problem_id'], ['id'])
    op.create_foreign_key(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_userdata', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_userdata_user_id_fkey'), 'micro_userdata', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'micro_todo', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_todo_user_id_fkey'), 'micro_todo', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_organization_member_user_id_fkey'), 'micro_organization_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_contest_language', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_contest_language_contest_id_fkey'), 'micro_contest_language', 'contest', ['contest_id'], ['id'])
    # ### end Alembic commands ###
