"""add_notification_table_real

Revision ID: 613f69dd0c7e
Revises: 47f37f1783cb
Create Date: 2026-02-27 16:02:28.768159

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '613f69dd0c7e'
down_revision: Union[str, None] = '47f37f1783cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_notification',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_micro_notification_id'), 'micro_notification', ['id'], unique=False, schema='public')
    op.drop_constraint(op.f('micro_contest_language_contest_id_fkey'), 'micro_contest_language', type_='foreignkey')
    op.create_foreign_key(None, 'micro_contest_language', 'contest', ['contest_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('micro_organization_contest_contest_id_fkey'), 'micro_organization_contest', type_='foreignkey')
    op.drop_constraint(op.f('micro_organization_contest_organization_id_fkey'), 'micro_organization_contest', type_='foreignkey')
    op.create_foreign_key(None, 'micro_organization_contest', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'micro_organization_contest', 'contest', ['contest_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('micro_organization_member_user_id_fkey'), 'micro_organization_member', type_='foreignkey')
    op.drop_constraint(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', type_='foreignkey')
    op.create_foreign_key(None, 'micro_organization_member', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.drop_constraint(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.create_foreign_key(None, 'micro_problem_code', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_problem_code', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('micro_todo_user_id_fkey'), 'micro_todo', type_='foreignkey')
    op.create_foreign_key(None, 'micro_todo', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('micro_userdata_user_id_fkey'), 'micro_userdata', type_='foreignkey')
    op.create_foreign_key(None, 'micro_userdata', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.drop_constraint(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.create_foreign_key(None, 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', 'problem', ['problem_id'], ['id'])
    op.create_foreign_key(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_userdata', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_userdata_user_id_fkey'), 'micro_userdata', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'micro_todo', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_todo_user_id_fkey'), 'micro_todo', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_organization_member_user_id_fkey'), 'micro_organization_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_organization_contest', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_organization_contest', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_organization_contest_organization_id_fkey'), 'micro_organization_contest', 'micro_organization', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('micro_organization_contest_contest_id_fkey'), 'micro_organization_contest', 'contest', ['contest_id'], ['id'])
    op.drop_constraint(None, 'micro_contest_language', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_contest_language_contest_id_fkey'), 'micro_contest_language', 'contest', ['contest_id'], ['id'])
    op.drop_index(op.f('ix_public_micro_notification_id'), table_name='micro_notification', schema='public')
    op.drop_table('micro_notification', schema='public')
    # ### end Alembic commands ###
