"""update userdata 

Revision ID: 81aa563a53b1
Revises: 613f69dd0c7e
Create Date: 2026-03-04 14:05:22.111461

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from migrations.migration_helpers import drop_constraint_if_exists, drop_fk_referencing_column

# revision identifiers, used by Alembic.
revision: str = '81aa563a53b1'
down_revision: Union[str, None] = '613f69dd0c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # --- Helper: add BaseEntity columns (created_time, updated_time) if missing ---
    def _ensure_base_entity_columns(table_name: str, schema: str = "public"):
        cols = {c["name"] for c in inspector.get_columns(table_name, schema=schema)}
        if "created_time" not in cols:
            op.add_column(
                table_name,
                sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
                schema=schema,
            )
        if "updated_time" not in cols:
            op.add_column(
                table_name,
                sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
                schema=schema,
            )

    # Ensure all micro_ tables have BaseEntity columns
    for tbl in [
        'micro_userdata', 'micro_organization', 'micro_organization_member',
        'micro_contest_language', 'micro_organization_contest', 'micro_problem_code',
        'micro_todo', 'micro_workbook', 'micro_notification', 'micro_contest_user',
    ]:
        if inspector.has_table(tbl, schema='public'):
            _ensure_base_entity_columns(tbl)

    drop_constraint_if_exists('micro_contest_language', 'micro_contest_language_contest_id_fkey')
    op.create_foreign_key(None, 'micro_contest_language', 'contest', ['contest_id'], ['id'], source_schema='public', referent_schema='public')

    drop_constraint_if_exists('micro_notification', 'micro_notification_user_id_fkey')
    op.create_foreign_key(None, 'micro_notification', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')

    drop_constraint_if_exists('micro_organization_contest', 'micro_organization_contest_contest_id_fkey')
    drop_constraint_if_exists('micro_organization_contest', 'micro_organization_contest_organization_id_fkey')
    op.create_foreign_key(None, 'micro_organization_contest', 'contest', ['contest_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'micro_organization_contest', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public')

    # Handle both user_id and member_id schemas
    drop_fk_referencing_column('micro_organization_member', 'organization_id')
    drop_fk_referencing_column('micro_organization_member', 'user_id')
    drop_constraint_if_exists('micro_organization_member', 'micro_organization_member_user_id_fkey')
    drop_constraint_if_exists('micro_organization_member', 'micro_organization_member_member_id_fkey')
    drop_constraint_if_exists('micro_organization_member', 'micro_organization_member_organization_id_fkey')
    op.create_foreign_key(None, 'micro_organization_member', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')

    drop_constraint_if_exists('micro_problem_code', 'micro_problem_code_problem_id_fkey')
    drop_constraint_if_exists('micro_problem_code', 'micro_problem_code_user_id_fkey')
    op.create_foreign_key(None, 'micro_problem_code', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_problem_code', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')

    drop_constraint_if_exists('micro_todo', 'micro_todo_user_id_fkey')
    op.create_foreign_key(None, 'micro_todo', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')

    # Add dark_mode_enabled / language_preferences if missing
    userdata_cols = {c["name"] for c in inspector.get_columns("micro_userdata", schema="public")}
    if "dark_mode_enabled" not in userdata_cols:
        op.add_column(
            'micro_userdata',
            sa.Column(
                'dark_mode_enabled',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false'),
            ),
        )
    if "language_preferences" not in userdata_cols:
        op.add_column(
            'micro_userdata',
            sa.Column(
                'language_preferences',
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
                server_default=sa.text("'[\"c\", \"cpp\", \"python\", \"java\", \"javascript\"]'::jsonb"),
            ),
        )
    drop_constraint_if_exists('micro_userdata', 'micro_userdata_user_id_fkey')
    op.create_foreign_key(None, 'micro_userdata', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')

    drop_constraint_if_exists('micro_workbook_problem', 'micro_workbook_problem_problem_id_fkey')
    drop_constraint_if_exists('micro_workbook_problem', 'micro_workbook_problem_workbook_id_fkey')
    op.create_foreign_key(None, 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', 'problem', ['problem_id'], ['id'])
    op.drop_constraint(None, 'micro_userdata', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_userdata_user_id_fkey'), 'micro_userdata', 'user', ['user_id'], ['id'])
    op.drop_column('micro_userdata', 'language_preferences')
    op.drop_column('micro_userdata', 'dark_mode_enabled')
    op.drop_constraint(None, 'micro_todo', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_todo_user_id_fkey'), 'micro_todo', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_organization_member_user_id_fkey'), 'micro_organization_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_organization_contest', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_organization_contest', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_organization_contest_organization_id_fkey'), 'micro_organization_contest', 'micro_organization', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('micro_organization_contest_contest_id_fkey'), 'micro_organization_contest', 'contest', ['contest_id'], ['id'])
    op.drop_constraint(None, 'micro_notification', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_notification_user_id_fkey'), 'micro_notification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_contest_language', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_contest_language_contest_id_fkey'), 'micro_contest_language', 'contest', ['contest_id'], ['id'])
    # ### end Alembic commands ###
