"""empty message

Revision ID: b5873c6d6d15
Revises: 9ff40babf0d0
Create Date: 2026-02-26 15:04:58.013774

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from migrations.migration_helpers import drop_constraint_if_exists, drop_fk_referencing_column


# revision identifiers, used by Alembic.
revision: str = 'b5873c6d6d15'
down_revision: Union[str, None] = '9ff40babf0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    drop_constraint_if_exists('micro_contest_language', 'micro_contest_language_contest_id_fkey')
    op.create_foreign_key(None, 'micro_contest_language', 'contest', ['contest_id'], ['id'], source_schema='public', referent_schema='public')

    drop_constraint_if_exists('micro_organization_contest', 'micro_organization_contest_contest_id_fkey')
    drop_constraint_if_exists('micro_organization_contest', 'micro_organization_contest_organization_id_fkey')
    op.create_foreign_key(None, 'micro_organization_contest', 'contest', ['contest_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'micro_organization_contest', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public')

    # Handle both user_id and member_id schemas
    drop_fk_referencing_column('micro_organization_member', 'organization_id')
    drop_fk_referencing_column('micro_organization_member', 'user_id')
    drop_constraint_if_exists('micro_organization_member', 'micro_organization_member_user_id_fkey')
    drop_constraint_if_exists('micro_organization_member', 'micro_organization_member_member_id_fkey')
    drop_constraint_if_exists('micro_organization_member', 'micro_organization_member_organization_id_fkey')
    op.create_foreign_key(None, 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_organization_member', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')

    drop_constraint_if_exists('micro_problem_code', 'micro_problem_code_user_id_fkey')
    drop_constraint_if_exists('micro_problem_code', 'micro_problem_code_problem_id_fkey')
    op.create_foreign_key(None, 'micro_problem_code', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_problem_code', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')

    drop_constraint_if_exists('micro_todo', 'micro_todo_user_id_fkey')
    op.create_foreign_key(None, 'micro_todo', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')

    drop_constraint_if_exists('micro_userdata', 'micro_userdata_user_id_fkey')
    op.create_foreign_key(None, 'micro_userdata', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')

    drop_constraint_if_exists('micro_workbook_problem', 'micro_workbook_problem_workbook_id_fkey')
    drop_constraint_if_exists('micro_workbook_problem', 'micro_workbook_problem_problem_id_fkey')
    op.create_foreign_key(None, 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', 'problem', ['problem_id'], ['id'])
    op.create_foreign_key(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_userdata', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_userdata_user_id_fkey'), 'micro_userdata', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'micro_todo', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_todo_user_id_fkey'), 'micro_todo', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_organization_member_user_id_fkey'), 'micro_organization_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'micro_organization_contest', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_organization_contest', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_organization_contest_organization_id_fkey'), 'micro_organization_contest', 'micro_organization', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('micro_organization_contest_contest_id_fkey'), 'micro_organization_contest', 'contest', ['contest_id'], ['id'])
    op.drop_constraint(None, 'micro_contest_language', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_contest_language_contest_id_fkey'), 'micro_contest_language', 'contest', ['contest_id'], ['id'])
    # ### end Alembic commands ###
