"""empty message

Revision ID: bc0563f34598
Revises: e1c2ed29b7d3
Create Date: 2025-10-30 11:17:06.819188

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0563f34598'
down_revision: Union[str, None] = 'e1c2ed29b7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('micro_organization_member', sa.Column('member_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('micro_organization_member_user_id_fkey'), 'micro_organization_member', type_='foreignkey')
    op.drop_constraint(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', type_='foreignkey')
    op.create_foreign_key(None, 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_organization_member', 'user', ['member_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_column('micro_organization_member', 'user_id')
    op.drop_constraint(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.drop_constraint(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', type_='foreignkey')
    op.create_foreign_key(None, 'micro_problem_code', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'micro_problem_code', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.drop_constraint(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.create_foreign_key(None, 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', 'problem', ['problem_id'], ['id'])
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_problem_code', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_problem_code_problem_id_fkey'), 'micro_problem_code', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_problem_code_user_id_fkey'), 'micro_problem_code', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('micro_organization_member', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_organization_member', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_organization_member_organization_id_fkey'), 'micro_organization_member', 'micro_organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_organization_member_user_id_fkey'), 'micro_organization_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_micro_org_member_unique'
      ) THEN
        ALTER TABLE public.micro_organization_member
        DROP CONSTRAINT uq_micro_org_member_unique;
      END IF;
    END
    $$;
    """)
    op.drop_column('micro_organization_member', 'member_id')
    # ### end Alembic commands ###
