"""init

Revision ID: d1b5e11a7f2b
Revises: 
Create Date: 2025-11-30 13:20:57.271820

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b5e11a7f2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_contest_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'user_id', name='uq_micro_contest_user_contest_user'),
    schema='public'
    )
    op.create_index(op.f('ix_public_micro_contest_user_contest_id'), 'micro_contest_user', ['contest_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_micro_contest_user_id'), 'micro_contest_user', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_micro_contest_user_user_id'), 'micro_contest_user', ['user_id'], unique=False, schema='public')
    op.create_table('micro_organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_micro_organization_description'), 'micro_organization', ['description'], unique=False, schema='public')
    op.create_index(op.f('ix_public_micro_organization_id'), 'micro_organization', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_micro_organization_name'), 'micro_organization', ['name'], unique=False, schema='public')
    op.create_table('micro_workbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_micro_workbook_id'), 'micro_workbook', ['id'], unique=False, schema='public')
    op.create_table('micro_organization_member',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['public.user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['public.micro_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'member_id'),
    sa.UniqueConstraint('organization_id', 'member_id', name='uq_micro_org_member_unique'),
    schema='public'
    )
    op.create_table('micro_userdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('student_id', sa.Text(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id'),
    schema='public'
    )
    op.create_table('micro_problem_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['public.problem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'user_id', 'language', name='uq_micro_problem_code_pul'),
    schema='public'
    )
    op.create_index(op.f('ix_public_micro_problem_code_id'), 'micro_problem_code', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_micro_problem_code_problem_id'), 'micro_problem_code', ['problem_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_micro_problem_code_user_id'), 'micro_problem_code', ['user_id'], unique=False, schema='public')
    op.create_table('micro_workbook_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workbook_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['public.problem.id'], ),
    sa.ForeignKeyConstraint(['workbook_id'], ['public.micro_workbook.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_micro_workbook_problem_id'), 'micro_workbook_problem', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_micro_workbook_problem_id'), table_name='micro_workbook_problem', schema='public')
    op.drop_table('micro_workbook_problem', schema='public')
    op.drop_index(op.f('ix_public_micro_problem_code_user_id'), table_name='micro_problem_code', schema='public')
    op.drop_index(op.f('ix_public_micro_problem_code_problem_id'), table_name='micro_problem_code', schema='public')
    op.drop_index(op.f('ix_public_micro_problem_code_id'), table_name='micro_problem_code', schema='public')
    op.drop_table('micro_problem_code', schema='public')
    op.drop_table('micro_userdata', schema='public')
    op.drop_table('micro_organization_member', schema='public')
    op.drop_index(op.f('ix_public_micro_workbook_id'), table_name='micro_workbook', schema='public')
    op.drop_table('micro_workbook', schema='public')
    op.drop_index(op.f('ix_public_micro_organization_name'), table_name='micro_organization', schema='public')
    op.drop_index(op.f('ix_public_micro_organization_id'), table_name='micro_organization', schema='public')
    op.drop_index(op.f('ix_public_micro_organization_description'), table_name='micro_organization', schema='public')
    op.drop_table('micro_organization', schema='public')
    op.drop_index(op.f('ix_public_micro_contest_user_user_id'), table_name='micro_contest_user', schema='public')
    op.drop_index(op.f('ix_public_micro_contest_user_id'), table_name='micro_contest_user', schema='public')
    op.drop_index(op.f('ix_public_micro_contest_user_contest_id'), table_name='micro_contest_user', schema='public')
    op.drop_table('micro_contest_user', schema='public')
    # ### end Alembic commands ###
