"""empty message

Revision ID: f0bcb6bfed55
Revises: 202410010001
Create Date: 2025-10-16 00:37:11.551658

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bcb6bfed55'
down_revision: Union[str, None] = '202410010001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro_problem_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['public.problem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'user_id', 'language', name='uq_micro_problem_code_pul'),
    schema='public'
    )
    op.create_index(op.f('ix_public_micro_problem_code_id'), 'micro_problem_code', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_micro_problem_code_problem_id'), 'micro_problem_code', ['problem_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_micro_problem_code_user_id'), 'micro_problem_code', ['user_id'], unique=False, schema='public')
    op.alter_column('micro_workbook', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_public_micro_workbook_problem_problem_id'), table_name='micro_workbook_problem')
    op.drop_index(op.f('ix_public_micro_workbook_problem_workbook_id'), table_name='micro_workbook_problem')
    op.drop_constraint(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.drop_constraint(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', type_='foreignkey')
    op.create_foreign_key(None, 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_public_micro_workbook_problem_workbook_id'), 'micro_workbook_problem', ['workbook_id'], unique=False)
    op.create_index(op.f('ix_public_micro_workbook_problem_problem_id'), 'micro_workbook_problem', ['problem_id'], unique=False)
    op.alter_column('micro_workbook', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_public_micro_problem_code_user_id'), table_name='micro_problem_code', schema='public')
    op.drop_index(op.f('ix_public_micro_problem_code_problem_id'), table_name='micro_problem_code', schema='public')
    op.drop_index(op.f('ix_public_micro_problem_code_id'), table_name='micro_problem_code', schema='public')
    op.drop_table('micro_problem_code', schema='public')
    # ### end Alembic commands ###
