"""empty message

Revision ID: f0bcb6bfed55
Revises: 202410010001
Create Date: 2025-10-16 00:37:11.551658

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bcb6bfed55'
down_revision: Union[str, None] = '202410010001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # micro_problem_code는 이전 리비전(8e0e5ccc26a0)에서 이미 생성됨
    # 따라서 이 파일에서는 해당 테이블 작업을 제거해야 함.

    # 아래 세 줄만 남기면 충분함.
    op.alter_column(
        'micro_workbook',
        'is_public',
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text('false')
    )

    op.drop_index(
        op.f('ix_public_micro_workbook_problem_problem_id'),
        table_name='micro_workbook_problem'
    )
    op.drop_index(
        op.f('ix_public_micro_workbook_problem_workbook_id'),
        table_name='micro_workbook_problem'
    )
    op.drop_constraint(
        op.f('micro_workbook_problem_problem_id_fkey'),
        'micro_workbook_problem',
        type_='foreignkey'
    )
    op.drop_constraint(
        op.f('micro_workbook_problem_workbook_id_fkey'),
        'micro_workbook_problem',
        type_='foreignkey'
    )
    op.create_foreign_key(
        None,
        'micro_workbook_problem',
        'problem',
        ['problem_id'],
        ['id'],
        source_schema='public',
        referent_schema='public'
    )
    op.create_foreign_key(
        None,
        'micro_workbook_problem',
        'micro_workbook',
        ['workbook_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
        ondelete='CASCADE'
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'micro_workbook_problem', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('micro_workbook_problem_workbook_id_fkey'), 'micro_workbook_problem', 'micro_workbook', ['workbook_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('micro_workbook_problem_problem_id_fkey'), 'micro_workbook_problem', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_public_micro_workbook_problem_workbook_id'), 'micro_workbook_problem', ['workbook_id'], unique=False)
    op.create_index(op.f('ix_public_micro_workbook_problem_problem_id'), 'micro_workbook_problem', ['problem_id'], unique=False)
    op.alter_column('micro_workbook', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_public_micro_problem_code_user_id'), table_name='micro_problem_code', schema='public')
    op.drop_index(op.f('ix_public_micro_problem_code_problem_id'), table_name='micro_problem_code', schema='public')
    op.drop_index(op.f('ix_public_micro_problem_code_id'), table_name='micro_problem_code', schema='public')
    op.drop_table('micro_problem_code', schema='public')
    # ### end Alembic commands ###
