# Generated by Django 3.2.25 on 2025-08-06 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '__first__'),
        ('problem', '0015_auto_20250806_0332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problembookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='problembookmark',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problembookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProblemCategory',
        ),
        migrations.RemoveField(
            model_name='problemcomment',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problemcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='tags_custom',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='view_count',
        ),
        migrations.AddField(
            model_name='problem',
            name='workbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workbook.workbook'),
        ),
        migrations.DeleteModel(
            name='ProblemBookmark',
        ),
        migrations.DeleteModel(
            name='ProblemComment',
        ),
    ]
