from enum import Enum


class ErrorCode(str, Enum):
    # Common

    BAD_REQUEST = "COMMON_400"
    UNAUTHORIZED = "AUTH_401"
    FORBIDDEN = "AUTH_403"
    NOT_FOUND = "COMMON_404"
    CONFLICT = "COMMON_409"
    INTERNAL_SERVER_ERROR = "SERVER_500"

    # Auth
    INVALID_CREDENTIALS = "AUTH_400"
    TOKEN_EXPIRED = "AUTH_401_1"
    TOKEN_INVALID = "AUTH_401_2"
    TFA_REQUIRED = "AUTH_403_1"
    TFA_INVALID = "AUTH_403_2"

    # User
    USER_NOT_FOUND = "USER_404"
    USER_ALREADY_EXISTS = "USER_409"
    STUDENT_ID_ALREADY_EXISTS = "USER_409_1"
    EMAIL_ALREADY_EXISTS = "USER_409_2"
    USER_DISABLED = "USER_403"

    # Problem
    PROBLEM_NOT_FOUND = "PROBLEM_404_1"
    POLLING_NOT_FOUND = "PROBLEM_404_2"
    PROBLEM_ALREADY_EXISTS = "PROBLEM_409"
    PROBLEM_NOT_VISIBLE = "PROBLEM_403"
    PROBLEM_IMPORT_FORMAT_ERROR = "PROBLEM_400_1"
    PROBLEM_IMPORT_MISSING_FILE = "PROBLEM_400_2"
    PROBLEM_IMPORT_INVALID_METADATA = "PROBLEM_400_3"
    PROBLEM_TEST_CASE_NOT_MATCH = "PROBLEM_400_4"
    PROBLEM_TEST_CASE_NOT_FOUND = "PROBLEM_404_3"
    PROBLEM_JUDGE_SERVER_ERROR = "PROBLEM_500_1"
    PROBLEM_EXPORT_INVALID_JSON = "PROBLEM_400_5"
    PROBLEM_EXPORT_UNSUPPORTED_VERSION = "PROBLEM_400_6"
    PROBLEM_EXPORT_VALIDATION_ERROR = "PROBLEM_400_7"

    # Contest
    CONTEST_NOT_FOUND = "CONTEST_404"
    CONTEST_NOT_STARTED = "CONTEST_400_1"
    CONTEST_ENDED = "CONTEST_400_2"
    CONTEST_USER_NOT_IN_ORGANIZATION = "CONTEST_401_1"
    CONTEST_PASSWORD_REQUIRED = "CONTEST_403_1"
    CONTEST_PASSWORD_INVALID = "CONTEST_403_2"
    CONTEST_ACCESS_DENIED = "CONTEST_403"
    CONTEST_ANNOUNCEMENT_NOT_FOUND = "CONTEST_404_1"

    # Submission
    SUBMISSION_NOT_FOUND = "SUBMISSION_404"
    SUBMISSION_TOO_FREQUENT = "SUBMISSION_429"

    # Organization
    USER_NOT_IN_ORGANIZATION = "ORGANIZATION_400_1"
    ORGANIZATION_FORBIDDEN = "ORGANIZATION_401"
    ORGANIZATION_NOT_FOUND = "ORGANIZATION_404"
    ORGANIZATION_USER_NOT_FOUND = "ORGANIZATION_404_1"
    ORGANIZATION_USER_ALREADY_EXIST = "ORGANIZATION_409"
    ORGANIZATION_ALREADY_EXISTS = "ORGANIZATION_409"
    USER_ALREADY_IN_ORGANIZATION = "ORGANIZATION_409_1"

    # Workbook
    WORKBOOK_NOT_FOUND = "WORKBOOK_404"
    WORKBOOK_ALREADY_EXISTS = "WORKBOOK_409"
    WORKBOOK_PROBLEM_ALREADY_EXISTS = "WORKBOOK_409_1"

    # Pending
    PENDING_BAD_REQUEST = "PENDING_400"
    PENDING_ALREADY_DONE = "PENDING_400_1"
    PENDING_HAS_EXPIRED = "PENDING_400_2"
    PENDING_NOT_FOUND = "PENDING_404"
